import {StyleSheet} from 'react-native';

export const Styles = {
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    height: 600,
    width: 400,
  },
  logIpt: {
    borderWidth: 1,
    borderColor: "black",
    borderRadius: 5,
    marginTop: 5,
    height: 40,
    marginBottom: 10
  },
  btnLog: {
    backgroundColor: "black",
    width: 100,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 5,
    borderRadius: 5,
  },
  btnCircle: {
    borderWidth:1,
    borderColor:'gray',
    alignItems:'center',
    justifyContent:'center',
    width:100,
    height:100,
    backgroundColor:'gray',
    borderRadius:100,
    marginRight: 15,
  },
  tab1: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: 15,
    paddingTop: 25,
  },
  footer: {
    backgroundColor: "white",
  },
  TabHeading1: {
    backgroundColor: 'white',
    borderWidth: 0.5,
    borderColor: "red",
    borderRadius: 0,
    borderBottomWidth: 7,
    borderBottomColor: "#33CCFF",
  },
  TabHeading2: {
    backgroundColor: 'white',
    borderWidth: 0.5,
    borderColor: "yellow",
    borderRadius: 0,
    borderBottomWidth: 7,
    borderBottomColor: "#33CCFF",
  },
  TabHeading3: {
    backgroundColor: 'white',
    borderWidth: 0.5,
    borderColor: "green",
    borderRadius: 0,
    borderBottomWidth: 7,
    borderBottomColor: "#33CCFF",
  },
  TabHeading4: {
    backgroundColor: 'white',
    borderWidth: 0.5,
    borderColor: "cyan",
    borderRadius: 0,
    borderBottomWidth: 7,
    borderBottomColor: "#33CCFF",
  },
  activeStyle: {
    backgroundColor: "gray",
    height: 100,
  },
  listBtn1: {
    width: 150,
    backgroundColor: "#FFCC33",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 5,
    height: 50,
    marginRight: 10
  },
  listBtn2: {
    width: 150,
    backgroundColor: "gray",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 5,
    height: 50
  },
  imageStyle: {
    fontSize: 20,
    marginLeft:15,
    marginRight:20,
    alignSelf:'center',
    width:20,
    height:24,
    justifyContent:'center'
  },
  numKeyBtn: {
    width: 100,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 0.5,
    borderColor: "#EEEEEE",
    borderRadius: 5,
  },
  rowKey: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between"
  },
  numKey: {
    width: 100,
    height: 65,
    justifyContent: "center",
    alignItems: "center",
  },
  imgContent: {
    display: "flex",
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  imgContent2nd: {
    display: "flex",
    flex: 0.7,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
};